# run like
# gegede-cli TOAD_Concept.cfg -o toad_concept.gdml

[TOAD]
class               = duneggd.Det.TOAD.TOAD_Builder
subbuilders         = ['GArTPC']

## Parameters
buildGarTPC=True

###############################
# GArTPC TOAD
###############################
# A basic builder for a gas TPC for TOAD consisting of:
# - a cylindrical chamber with two endcaps filled with gas
# - a cylindrical pressure vessel with two endcaps 
# - cathode
# - field cage
# - OROC

[GArTPC]
class               = duneggd.SubDetector.GArTPC_TOAD.GArTPCBuilder
subbuilders         = []

# Bounding Volume
halfDimension       = {'rmin':Q('0mm'),'rmax':Q('71cm'),'dz':Q('73.6cm')}
# must be biger than the geometry to prevent overlaps with volTOAD

# Gaseous Chamber
chamberDimension    = { 'r':Q('70cm'),'dz':Q('73.6cm') }
# r is the inner radius of the vacuum vessel
# dz is the full length of th vacuum vessel without the doomed ends
GasType             = 'HP_Ar'
drift               = 'z'

# Pressure Vessel
pvThickness = Q("1cm")
pvMaterial = "Steel"

# Field Cage (Rings)
# dz copper distance is 2.5cm# dz copper distance is 2.5cm
fcInnerRadius = Q('55.5cm')
fcOuterRadius = Q("56.1cm")
fcRingThickness =Q("1cm")
fcRingSpacing = Q("2.5cm")
fcMaterial = "Copper"
fcNRings = "8"

# Offsets in z
# Measured distances
# Offset from the end of the rail on the OROC side
TerminatorOffset = Q("284mm")
# Distance between the terminator and the OROC
TerminatorOROCoffset = Q("10mm")
# Distance between the terminator and the first ring of the field cage
fcTerminatorFirstRingOffset = Q("43mm")

# Offset in y
orocOffset_y = Q("56mm") # calculated!
# measured distance from the top is 76 mm, from the bottom 188 mm
# distance of the OROC from the vessel if centered: 
# (inner diameter of the vessel)/2 - (length of the oroc)/2 = 132 mm
# shift in y = (inner diameter of the vessel)/2 - (length of the oroc)/2 - 76 mm
orocFrameOffset_y = Q("77.5mm") # calculated!
# distance of the frame from the Main top: 33m
# distance of the frame from the Main bottom: 76mm
# Half length of the frame (centered)
# (inner diameter of the vessel)/2 - 33 mm - 76 mm - 2*132 mm = 513.5 mm
# Hence if centered: 
# (inner diameter of the vessel)/2 - 513.5 mm = 186.5 mm
# Offset:
# 186.5 - 76 33 = 77.5 mm

# OROC alu main (full length dimensions)
orocMaterial =  "Aluminum"
orocUpper_dx1 = Q("467.747mm")
orocLower_dx2  =  Q("870.478mm")
orocThickness_dy1  =  Q("21.8mm")
# orocThickness_dy2=  Q("21.8mm") # same thickness everywhere
orocHeight_dz =  Q("1142mm")

# OROC alu pad frame
orocFrameThickness_dy1  =  Q("62mm")
#orocFrameThickness_dy2  =  Q("62mm") # same
orocFrameHeight_dz = Q("1027mm")
orocFrameVerticalDivisionThickness_dx1 = Q("16mm")
#orocFrameVerticalDivisionThickness_dx2 = Q("16mm") # same
orocFrameVerticalDivisionDepth_dy1 = Q("42.5mm")
#orocFrameVerticalDivisionDepth_dy2 = Q("42.5mm") # same

# Steel Cathode
# "mesh" thin steel ring with a thicker disk around it
CathodeMaterial  = "Steel" # steel mesh wires
CathodeThickness = Q("0.025mm") # thickness of the mesh is about 25 microns
CathodeInnerRadius =  Q("0mm") # radius
CathodeOuterRadius =  Q("56cm") # solid ring

# Steel Cathode Holder
CathodeHolderMaterial = "Steel"
CathodeHolderThickness = Q("3mm")  #steel ring is 3mm wide
CathodeHolderInnerRadius = Q("56cm")
CathodeHolderOuterRadius= Q("59cm")

# Terminator 
TerminatorMaterial = "Steel"
TerminatorThickness = Q("1mm")
TerminatorInnerRadius = Q("0cm")
TerminatorOuterRadius = Q("56cm")

# Terminator Holder
TerminatorHolderMaterial = "PVC"
TerminatorHolderThickness = Q("1mm")
TerminatorHolderInnerRadius = Q("56cm")
TerminatorHolderOuterRadius = Q("59cm")